### ISSUE TITLE
Habbo Camera dont work

### ISSUE THREAD

**Issue by KilluaKira** [sant0ro/habbo-camera-server#10]
http://prntscr.com/ab8492

**Comment by sant0ro** [comment]
Habbo Camera API isn't made to be accessed by Navigator.

https://github.com/sant0ro/habbo-camera-server/issues/5

**Comment by KilluaKira** [comment]
Yes i understand http://prntscr.com/ab8sny

**Comment by sant0ro** [comment]
Read entire Issue. and You need Run Asset Extractor. And configure everything.
