### ISSUE TITLE
Wall/floor masks aren't skewed properly

### ISSUE THREAD

**Issue by scottstamp** [sant0ro/habbo-camera-server#2]
http://i.imgur.com/7sXXsoY.png

:(

**Comment by sant0ro** [comment]
Hello Wall and Floor Masks are the Wallpaper and Floorpaper.
That happens because the Image Rotation. i Will code that just wait.

**Comment by sant0ro** [comment]
Okay. Changing code to use: http://php.net/manual/en/function.imagerotate.php
(That is better than imageflip, because imageflip will not do what we need in this part. Flipping image will only change angle. Rotating the masks will change the displaying point.) 
Thanks!
