### ISSUE TITLE
Door Y Position

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/habbo-camera-server#4]
The Door Y position is correct now.
Weirdly, the given Y position is the Z position, and need to pick this "Z", and the given "X", to reach the "Y" position. By Pitagoras-Inversed Theorem: C² = B² - A², so C = A - B (in a little few words)
But that gives to use 98% correct Y position, the door someway is a little more aligned on botton..

**Comment by DJGOMEZV** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/14180119/9736240/d03e1536-5609-11e5-9141-c5466917e8ca.png)

Help Me Please.

**Comment by sant0ro** [comment]
You Need use the Import Script. As cited on the Documentation.
Only putting the Sprites, the Camera will Work.

**Comment by DJGOMEZV** [comment]
Could you tell me how I do it?

**Comment by sant0ro** [comment]
If YOU OPEN THE DOCUMENTATION IN THE PHP FILE, I THINK YOU CAN SEE WHERE MUST DOWNLOAD. PLEASE HERE IS A ISSUE. NOT A HELP SECTION.
I will not answer anymore Helps, about things that works if you not read the documentation.
Thanks.

**Comment by DJGOMEZV** [comment]
Ok now I download the documentation, opened assets.php, figures.php and sprites.php I download a number of files (images) now those folders (masks and sprites) hit where the server is the camera? just answer me this and not come back to ask for help

**Comment by sant0ro** [comment]
first: the asset downloader create the right folders. only copy into the same folder that servercamera.php is. OBSERVATION: DOWNLOAD ALL ASSETS can SPEND LIKE MANY HOURS.
minimum files downloaded: 20.000,00

**Comment by DJGOMEZV** [comment]
now shows pictures floor, but still shows the door and the user, and download all files.

**Comment by sant0ro** [comment]
Sorry but your english is supa bad, repeat plz. And i'm saying again. Read the documentation. Or i will block your access from this repository.

**Comment by DJGOMEZV** [comment]
Speak Spanish? My English is Bad.
