### ISSUE TITLE
problem with installing of servercamera.php

### ISSUE THREAD

**Issue by xJuice** [sant0ro/habbo-camera-server#8]
I have installationproblem

Open:

http://localhost/game/ServerCamera.php?install?true

on php 5.4 : Error:

 Parse error: syntax error, unexpected '=', expecting ')' in D:\inetpub\wwwroot\camera\ServerCamera.php on line 177

on PHP 5.5:

Oh No! (#500)
We really sorry, but the following error happend:

    the php input, isn't a valid jSON data!

**Comment by xJuice** [comment]
switch ($action_name):
            case 'run':
                header('Content-Type:text/html; charset=UTF-8');
                return $this->do_it(file_get_contents('php://input'), false, 1);
            case 'room':
                header('Content-Type:text/html; charset=UTF-8');
                return $this->do_it(file_get_contents('php://input'), false, 2);
            case 'install':
                header('Content-Type:text/html; charset=UTF-8');
                return $this->create_folders();
            case 'test_camera':
                header('Content-Type: image/png');
                return $this->test_camera(1);
            case 'test_room':
                header('Content-Type: image/png');
                return $this->test_camera(2);
            default:
                header('Content-Type:text/html; charset=UTF-8');
                return $this->just_die('001', 'this action doesn\'t exists', true);
        endswitch;
    }

**Comment by sant0ro** [comment]
?install=true
